---
version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pizza_shop
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: pizza_password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_network

  redis:
    image: redis:6
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pizza_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "4345:8080"
    networks:
      - pizza_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  pizza_network:
    driver: bridge
