# Generated by Django 5.1.1 on 2024-09-14 18:23

from django.db import migrations, models

import apps.pizza_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_shop", "0003_rename_price_modifier_crust_price_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    apps.pizza_shop.models.PrefixedULIDField(
                        db_index=True,
                        editable=False,
                        max_length=30,
                        prefix="sz",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price_modifier", models.DecimalField(decimal_places=2, max_digits=4)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
