name: manual-deploy

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Deployment target host"
        type: string
        required: true

env:
  PythonVersion: "3.12.3"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3.2.4
        id: cache
        with:
          path: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}
          key: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}/${{ runner.arch }}-${{ hashFiles('requirements*.txt') }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-1|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Identify deploy target
        run: echo "Would deploy to $DEPLOY_TARGET"
        env:
          DEPLOY_TARGET: ${{ inputs.deploy_target }}
