name: build-frontend

on:
  pull_request:
    paths: ["**/frontend/**"]

env:
  PythonVersion: "3.12.3"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}
          key: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}/${{ runner.arch }}-${{ hashFiles('requirements*.txt') }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
      - name: Build frontend
        run: ./scripts/ci-build-frontend.sh
