name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  PythonVersion: "3.12.3"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3.2.4
        id: cache
        with:
          path: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}
          key: ${{ runner.tool_cache }}/Python/${{ env.PythonVersion }}/${{ runner.arch }}-${{ hashFiles('requirements*.txt') }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-1|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.1
